[Compression app]: add tests
mate-academy/node_compression-app pull request #75
Opened 2024-01-18 15:42 UTC by sergii-nosachenko

## Description

Added tests, improved readme

### Screenshots

<img width="867" alt="Screenshot 2024-01-18 at 17 30 23" src="https://github.com/mate-academy/node_compression-app/assets/54940595/da2015da-45f2-498c-8d81-45fb2d682a96">

2024-01-18 16:23 UTC, alexandra-protyanova approved these changes
my like goes here

2024-01-18 16:23 UTC, alexandra-protyanova commented on tests/createServer.test.js
> +        const expectedOptions = ['gzip', 'deflate', 'br'];
```suggestion
        const expectedOptions = Object.keys(compressionTypes)
```

2024-01-18 16:23 UTC, alexandra-protyanova commented on tests/createServer.test.js
> +      it('should return a a page with a submit button', async() => {
```suggestion
      it('should return a page with a submit button', async() => {
```

2024-01-19 08:03 UTC, mgrinko requested changes

2024-01-19 08:03 UTC, mgrinko commented on tests/createServer.test.js
> +      expect(response).toBeUndefined();
And here is one more simpler alternative
```suggestion
      return expect(axios.get(COMPRESS_ENDPOINT))
        .rejects
        .its('response')
        .its('status')
        .toBe(400);
```

2024-01-22 07:03 UTC, mgrinko approved these changes

2024-01-22 07:03 UTC, mgrinko commented on tests/createServer.test.js
> +              );
```suggestion
              .then(res => decompress(res.data))
              .then(uncompressedData => {
                expect(uncompressedData.toString())
                  .toBe(content);
              });
```

2024-01-22 11:07 UTC, merged